### ISSUE TITLE
Adicionar Teste Unitario.

### ISSUE THREAD

**Issue by AndrewRSS** [HermmanGIT/listacanetas#17]
Adicionar Teste Unitário com a utilização do JUnit no cenário abaixo.

**Comment by HermmanGIT** [comment]
1.Caneta deve ter atributo para representar se está tampada
2.Caneta deve ter método para escrever uma String que recebe como parâmetro
3.Caneta só pode escrever se estiver destampada
4.O estado inicial da Caneta sempre é tampada
5.Apenas canetas em posições pares devem ser destampadas

**Comment by HermmanGIT** [comment]
Teste unitário adicionado.
