### ISSUE TITLE
Melhorar coesão do método listaCanetas na classe de Teste

### ISSUE THREAD

**Issue by alanrodrigues** [HermmanGIT/listacanetas#8]
Primeiramente, todo método deve estar no infinitivo. Ou seja, "listarCanetas", por exemplo.

Mas precisamos melhorar a coesão desse método, pois ele está fazendo duas coisas: criando a lista de canetas e imprimindo as informações das canetas.

Sugestão:
- ter um método para criar canetas e outro método para imprimir as informações, se necessário.

**Comment by HermmanGIT** [comment]
Foi corrigido a coesão no nome do método, e foi criado um metodo para gerar a lista de canetas que foi chamado de `criarListaCaneta` e outro para exibir a lista denominado de `exibirCanetas`.
