### ISSUE TITLE
Ajustar nomes de variáveis na classe de Teste

### ISSUE THREAD

**Issue by alanrodrigues** [HermmanGIT/listacanetas#9]
Os nomes de variáveis (ou objetos) tem o padrão a ser seguido.
A primeira palavra é toda minúscula. Caso tenham duas ou mais palavras, a segunda em diante deve iniciar com a letra maiúscula. Ou seja: "canetasVermelhas".

O nome da variável usada no FOR foi "Caneta". Está errado, deveria ser "caneta" por tratar-se de um objeto. "Caneta" é a classe.

**Comment by HermmanGIT** [comment]
Os nomes das variáveis foram corrigidos.
